name: Deploy Ardent Collector to Production

# This deployment script assumes the following are configured in GitHub actions:
#
#  SSH_PRIVATE_KEY [secret]
#  DEPLOY_HOST [variable]
#  DEPLOY_USER [variable]
#  DEPLOY_DIR [variable]
#
# It also assumes that Node.js is installed, that PM2 is installed globally
# (e.g. `npm i pm2 -g`) and that the service has been started with `pm2`:
#
#  cd {DEPLOY_DIR}/{SERVICE_NAME}
#  pm2 start npm --name "{SERVICE_NAME}" -- run start
#
# DEPLOY_DIR should be an absolute path.
# SERVICE_NAME should match the name of the repository in GitHub.

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ vars.DEPLOY_HOST }}
        REMOTE_USER: ${{ vars.DEPLOY_USER }}
        TARGET: "${{ vars.DEPLOY_DIR }}/${{ env.SERVICE_NAME }}"
        EXCLUDE: ".git*, *.md, LICENSE, node_modules/"
        SCRIPT_AFTER: |
          cd "${{ vars.DEPLOY_DIR }}/${{ env.SERVICE_NAME }}"
          npm install --omit=dev 
          pm2 restart "${{ env.SERVICE_NAME }}" --cron-restart="55 7 * * *"
          echo $RSYNC_STDOUT